---
version: '2.4'

services:

  counsumer-app:
    build:
      context: C:\consumer\
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    healthcheck:
      test: "nc -z 127.0.0.1 8081"
      interval: 5s
      timeout: 1s
      retries: 10
    depends_on:
      kafka:
        condition: service_healthy

  producer-app:
    build: .
    ports:
      - 8080:8080
    healthcheck:
      test: "nc -z 127.0.0.1 8080"
      interval: 5s
      timeout: 1s
      retries: 10
    depends_on:
      kafka:
        condition: service_healthy

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181
    healthcheck:
      test: "nc -z 127.0.0.1 2181"
      interval: 5s
      timeout: 1s
      retries: 10

  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - 9092
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: "/opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper --list"
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
